services:
  - type: web
    name: whatsapp-bot-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        sync: false
      - key: SESSION_DIR
        value: ./auth_info
    autoDeploy: false
    branch: main
